// Copyright (c) 2026 whizBANG Developers LLC. All rights reserved.
// Licensed under AGPL-3.0 (Free) or BSL-1.1 (Solo/Team/Fabrick) with AI Training Restriction. See LICENSE.
//
// Applying a licence to a RUNNING process — the transition, which is the part nothing covered.
//
// Re-reading the licence on a timer made DNS publishing start and stop with the licence, and both
// ends of that were already tested: `license-watcher.spec.ts` covers resolving a snapshot from a
// key file, and
// `dns-writer.spec.ts` covers withdrawing a published zone. Neither covers the step between them,
// and that step is the only one that can leave a lapsed host serving a Solo zone forever — the
// resolver is gated on `services.weaver.dns.enable`, the OPTION, so it keeps answering from
// whatever Weaver wrote last.
//
// So `dns.stop` here is wired to the REAL `retireZone` against an in-memory filesystem, and the
// assertions read the resulting FILE. A fake that merely records "stop was called" would be a
// check on this module's own side of the seam: it would pass just as happily against a `stop`
// that returns without touching the zone, which is precisely the bug worth catching.
import { describe, it, expect, vi } from 'vitest'
import { createLicenseApplier, dnsPublishable, type LicenseConfigTarget } from '../../src/services/license-watcher.js'
import { retireZone } from '../../src/services/dns-writer.js'
import { TIERS } from '../../src/constants/vocabularies.js'

const HOSTS = '/var/lib/weaver/dns-hosts'

const PUBLISHED = [
  '# Generated by Weaver — DO NOT EDIT.',
  '# domain=vm.internal serial=7 ttl=60',
  '',
  '10.10.0.10\tweb.vm.internal\tweb',
  '',
].join('\n')

/**
 * A harness that is deliberately real where it matters.
 *
 * `dns.stop` runs the production `retireZone`; only the filesystem and the resolver signal are
 * injected, exactly as `dns-writer.spec.ts` injects them. `dns.start` stays a spy because starting
 * publication constructs a writer and a 30-second timer, neither of which has an observable
 * artifact to assert on — the withdrawal is the direction with a durable side effect.
 */
function harness(initialTier: string, zone: string | null = PUBLISHED) {
  const files: Record<string, string> = {}
  if (zone !== null) files[HOSTS] = zone

  const reload = vi.fn(async () => {})
  const dnsDeps = {
    writeFile: vi.fn(async (path: string, content: string) => { files[path] = content }),
    reload,
    readFile: vi.fn(async (path: string) => files[path] ?? null),
  }

  const config: LicenseConfigTarget = {
    tier: initialTier as LicenseConfigTarget['tier'],
    licenseExpiry: new Date('2026-06-01T00:00:00Z'),
    licenseGraceMode: false,
  }

  const start = vi.fn()
  const stop = vi.fn(async () => { await retireZone(dnsDeps, HOSTS) })
  const warn = vi.fn()
  const audit = vi.fn()
  // Declares its argument so the assertions can read `calls[0][0]`; a zero-parameter
  // double types `mock.calls` as an empty tuple.
  const notify = vi.fn(async (_event: unknown) => {})

  const applyLicense = createLicenseApplier({
    config,
    log: { warn },
    audit,
    notify,
    dns: { start, stop },
  })

  return { applyLicense, config, files, start, stop, warn, audit, notify, reload }
}

const snapshot = (tier: string, over: Partial<{ expiry: Date | null; graceMode: boolean }> = {}) => ({
  tier: tier as LicenseConfigTarget['tier'],
  expiry: new Date('2026-06-01T00:00:00Z'),
  graceMode: false,
  ...over,
})

describe('dnsPublishable', () => {
  it('licenses DNS Core at Solo and above', () => {
    expect(dnsPublishable(TIERS.FREE)).toBe(false)
    expect(dnsPublishable(TIERS.SOLO)).toBe(true)
    expect(dnsPublishable(TIERS.TEAM)).toBe(true)
    expect(dnsPublishable(TIERS.FABRICK)).toBe(true)
  })
})

describe('applying a licence across a lapse', () => {
  it('WITHDRAWS a published zone when the tier drops to Free', async () => {
    // The headline case: a Solo host publishing `.vm.internal` whose licence lapses. Before the
    // transition existed, the process simply stopped writing and dnsmasq kept serving the last
    // file — records frozen at the moment of lapse, drifting from reality thereafter.
    const { applyLicense, files } = harness(TIERS.SOLO)
    expect(files[HOSTS]).toContain('web.vm.internal')

    await applyLicense(snapshot(TIERS.FREE))

    expect(files[HOSTS]).not.toContain('web.vm.internal')
    expect(files[HOSTS]).not.toContain('10.10.0.10')
  })

  it('EMPTIES the zone rather than deleting it, and signals the resolver', async () => {
    // Both halves are load-bearing. dnsmasq refuses to start on a missing addn-hosts, and a
    // running one answers from the copy it read at start-up — so a withdrawal that skips the
    // reload leaves every withdrawn name resolving until something restarts.
    const { applyLicense, files, reload } = harness(TIERS.SOLO)

    await applyLicense(snapshot(TIERS.FREE))

    expect(HOSTS in files).toBe(true)
    expect(typeof files[HOSTS]).toBe('string')
    expect(reload).toHaveBeenCalledTimes(1)
  })

  it('applies the tier to the live config object BEFORE withdrawing', async () => {
    // Route plugins hold a reference to this object and read `tier` per request, so the mutation
    // is what makes the lapse reach `requireTier`. Asserted at the moment of withdrawal rather
    // than after: a `stop` that ran while the config still said Solo would be a window in which
    // the zone is gone but the API still serves Solo features.
    const config: LicenseConfigTarget = {
      tier: TIERS.SOLO,
      licenseExpiry: new Date('2026-06-01T00:00:00Z'),
      licenseGraceMode: false,
    }
    let tierAtWithdrawal: string | null = null

    const applyLicense = createLicenseApplier({
      config,
      log: { warn: vi.fn() },
      audit: vi.fn(),
      notify: vi.fn(async () => {}),
      dns: { start: vi.fn(), stop: vi.fn(async () => { tierAtWithdrawal = config.tier }) },
    })

    await applyLicense(snapshot(TIERS.FREE))

    expect(tierAtWithdrawal).toBe(TIERS.FREE)
    expect(config.tier).toBe(TIERS.FREE)
    expect(config.licenseGraceMode).toBe(false)
  })

  it('starts publishing when the tier rises to Solo', async () => {
    const { applyLicense, start, stop } = harness(TIERS.FREE, null)

    await applyLicense(snapshot(TIERS.SOLO))

    expect(start).toHaveBeenCalledTimes(1)
    expect(stop).not.toHaveBeenCalled()
  })

  it('does NOT withdraw when the tier is unchanged but the expiry moved', async () => {
    // A renewal is the common case and it must be invisible to DNS. Withdrawing here would drop
    // the zone of a customer who just PAID, on the poll that discovered their new key.
    const { applyLicense, files, stop, start } = harness(TIERS.SOLO)

    await applyLicense(snapshot(TIERS.SOLO, { expiry: new Date('2027-06-01T00:00:00Z') }))

    expect(stop).not.toHaveBeenCalled()
    expect(start).toHaveBeenCalledTimes(1)
    expect(files[HOSTS]).toContain('web.vm.internal')
  })

  it('keeps publishing through grace mode — grace retains the tier', async () => {
    // Grace is a paid tier whose key has expired, not a lapse. Withdrawing the zone here would
    // punish exactly the customer the grace window exists to protect.
    const { applyLicense, files, stop } = harness(TIERS.SOLO)

    await applyLicense(snapshot(TIERS.SOLO, { graceMode: true }))

    expect(stop).not.toHaveBeenCalled()
    expect(files[HOSTS]).toContain('web.vm.internal')
  })

  it('does nothing at all when the snapshot is identical', async () => {
    const { applyLicense, start, stop, audit, warn } = harness(TIERS.SOLO)

    await applyLicense(snapshot(TIERS.SOLO))

    expect(start).not.toHaveBeenCalled()
    expect(stop).not.toHaveBeenCalled()
    expect(audit).not.toHaveBeenCalled()
    expect(warn).not.toHaveBeenCalled()
  })

  it('withdraws only once across a repeated lapse', async () => {
    // The poll runs hourly. A host that stays Free must not re-signal the resolver every hour —
    // `retireZone` is idempotent by inspection, and this proves the transition inherits that.
    const { applyLicense, reload } = harness(TIERS.SOLO)

    await applyLicense(snapshot(TIERS.FREE))
    await applyLicense(snapshot(TIERS.FREE))
    await applyLicense(snapshot(TIERS.FREE))

    expect(reload).toHaveBeenCalledTimes(1)
  })

  it('withdraws on a downgrade that is still a paid tier', async () => {
    // Fabrick → Free is the obvious case; the one that gets missed is a drop that lands ABOVE
    // Free, where DNS stays licensed and must NOT be withdrawn.
    const { applyLicense, files, stop } = harness(TIERS.FABRICK)

    await applyLicense(snapshot(TIERS.SOLO))

    expect(stop).not.toHaveBeenCalled()
    expect(files[HOSTS]).toContain('web.vm.internal')
  })
})

describe('what an operator is told', () => {
  it('notifies at error severity on a downgrade', async () => {
    const { applyLicense, notify } = harness(TIERS.SOLO)

    await applyLicense(snapshot(TIERS.FREE))

    expect(notify).toHaveBeenCalledTimes(1)
    const n = notify.mock.calls[0]![0] as unknown as { severity: string; message: string; details: unknown }
    expect(n.severity).toBe('error')
    expect(n.message).toContain('downgraded')
    expect(n.details).toEqual({ from: TIERS.SOLO, to: TIERS.FREE, graceMode: false })
  })

  it('notifies at success severity on an upgrade', async () => {
    const { applyLicense, notify } = harness(TIERS.FREE, null)

    await applyLicense(snapshot(TIERS.SOLO))

    const n = notify.mock.calls[0]![0] as unknown as { severity: string }
    expect(n.severity).toBe('success')
  })

  it('audits every change, including one that does not move the tier', async () => {
    const { applyLicense, audit, notify } = harness(TIERS.SOLO)

    await applyLicense(snapshot(TIERS.SOLO, { graceMode: true }))

    expect(audit).toHaveBeenCalledTimes(1)
    expect(audit.mock.calls[0]![0]).toMatchObject({
      action: 'license.tier-changed',
      username: 'license-watcher',
      details: { from: TIERS.SOLO, to: TIERS.SOLO, graceMode: true },
    })
    // Entering grace is not a tier change, so it is audited but not announced as one.
    expect(notify).not.toHaveBeenCalled()
  })
})
