// Copyright (c) 2026 whizBANG Developers LLC. All rights reserved.
// Licensed under AGPL-3.0 (Free) or BSL-1.1 (Solo/Team/Fabrick) with AI Training Restriction. See LICENSE.
import { buildZone, renderHostsFile, zoneContentEquals, type DnsZone } from './dns-zone.js'

/**
 * Writes the generated zone to disk and asks the resolver to reload it.
 *
 * The filesystem and the reload are injected — the whole point of the class is what it does
 * ACROSS calls (skip an unchanged zone, advance the serial only on a real change, survive a
 * failed reload) and none of that is reachable in a test that needs a real dnsmasq.
 */
export interface DnsWriterDeps {
  /** Write a file atomically. Must not leave a partial file readable at `path`. */
  writeFile: (path: string, content: string) => Promise<void>
  /** Ask the resolver to re-read its hosts file. Rejects if the signal fails. */
  reload: () => Promise<void>
  now?: () => number
}

export interface DnsWriteResult {
  changed: boolean
  serial: number
  /** False when the zone changed on disk but the resolver did not pick it up. */
  reloaded: boolean
  skipped: DnsZone['skipped']
}

export class DnsZoneWriter {
  private lastZone: DnsZone | null = null
  private serial = 0

  constructor(
    private readonly deps: DnsWriterDeps,
    private readonly opts: { hostsPath: string; domain?: string; ttl?: number },
  ) {}

  get currentZone(): DnsZone | null {
    return this.lastZone
  }

  /**
   * Regenerate from a registry snapshot and publish if anything actually changed.
   *
   * Two orderings matter here and both are the opposite of the obvious one:
   *
   * 1. **Compare before incrementing the serial.** The serial is derived from the answer, so
   *    bumping it first makes every comparison report a change and the resolver reloads on every
   *    tick — for a service polled continuously, that is a reload storm that looks like nothing at
   *    all from the outside.
   *
   * 2. **Write, then reload; and keep the zone recorded even if the reload fails.** The file on
   *    disk IS the new state whether or not dnsmasq acknowledged it. Rolling `lastZone` back on a
   *    failed reload would make the next call see a change that has already been written, rewrite
   *    the identical file, and try again forever. Reporting `reloaded: false` lets the caller
   *    retry the *signal* without redoing the write.
   */
  async sync(workloads: { name: string; ip?: string }[]): Promise<DnsWriteResult> {
    const candidate = buildZone(workloads, {
      domain: this.opts.domain,
      ttl: this.opts.ttl,
      serial: this.serial,
    })

    if (this.lastZone && zoneContentEquals(this.lastZone, candidate)) {
      return { changed: false, serial: this.serial, reloaded: true, skipped: candidate.skipped }
    }

    this.serial += 1
    const zone: DnsZone = { ...candidate, serial: this.serial }

    await this.deps.writeFile(this.opts.hostsPath, renderHostsFile(zone))
    // Recorded BEFORE the reload — see (2) above. The disk is the state.
    this.lastZone = zone

    let reloaded = true
    try {
      await this.deps.reload()
    } catch {
      // Never rethrown: a resolver that will not reload is an operational problem, not a reason
      // to fail the workload operation that triggered this. The caller sees reloaded:false.
      reloaded = false
    }

    return { changed: true, serial: this.serial, reloaded, skipped: zone.skipped }
  }
}

/** The banner a retired zone carries, so the file explains itself to whoever opens it. */
export const RETIRED_ZONE_HEADER = [
  '# Generated by Weaver — DO NOT EDIT.',
  '# ZONE RETIRED. DNS Core is a Solo-and-above feature and this host is not licensed for it,',
  '# so Weaver is no longer maintaining these records and has withdrawn the ones it had published.',
  '# Install a licence and the zone republishes from the workload registry on the next sync.',
  '',
  '',
].join('\n')

export interface DnsRetireResult {
  /** True when a populated zone was found and withdrawn; false when there was nothing to do. */
  retired: boolean
  /** False when the file was emptied but the resolver did not pick it up. */
  reloaded: boolean
}

/**
 * Withdraw a previously published zone when the host is no longer licensed to serve one.
 *
 * The case: a Solo host publishes `.vm.internal`, its licence lapses to Free, and the backend
 * stops constructing a `DnsZoneWriter`. Nothing then maintains the file — but `weaver-dnsmasq` is
 * gated on `services.weaver.dns.enable`, the OPTION, not on the tier, so it keeps running and keeps
 * answering from the last zone Weaver wrote. A tier-gated feature outliving the tier, indefinitely,
 * with data that is frozen at the moment the licence expired and drifts from reality thereafter.
 *
 * **Emptied, never deleted.** The NixOS module creates this path via systemd-tmpfiles precisely
 * because "dnsmasq needs the file to exist before it starts, even empty — it refuses to start on a
 * missing addn-hosts". Removing it would trade a stale zone for a resolver that will not come back
 * after the next reboot, which is a strictly worse failure and one the operator would meet at the
 * least convenient time.
 *
 * **Idempotent by inspection.** It reads first and returns `retired: false` when the file is
 * absent or already carries the retirement banner, so an ordinary Free host neither creates a file
 * it never had nor signals the resolver on every boot.
 */
export async function retireZone(
  deps: Pick<DnsWriterDeps, 'writeFile' | 'reload'> & { readFile: (path: string) => Promise<string | null> },
  hostsPath: string,
): Promise<DnsRetireResult> {
  const existing = await deps.readFile(hostsPath)
  if (existing === null) return { retired: false, reloaded: true }
  if (existing.startsWith(RETIRED_ZONE_HEADER)) return { retired: false, reloaded: true }

  await deps.writeFile(hostsPath, RETIRED_ZONE_HEADER)

  // Emptying the file is not enough on its own: a running dnsmasq answers from the copy it read at
  // start-up, so without the signal the withdrawn names keep resolving until something else
  // restarts it. Same failure tolerance as `sync` — the disk is the state, and a resolver that
  // will not reload is an operational problem rather than a reason to fail start-up.
  let reloaded = true
  try {
    await deps.reload()
  } catch {
    reloaded = false
  }

  return { retired: true, reloaded }
}
