// Copyright (c) 2026 whizBANG Developers LLC. All rights reserved.
// Licensed under AGPL-3.0 (Free) or BSL-1.1 (Solo/Team/Fabrick) with AI Training Restriction. See LICENSE.
/**
 * Tier-Capabilities Generator (harness tier axis — Decision #185 / #178)
 *
 * Reads the 4-tier product matrix `code/tier-matrix.json` and emits the
 * harness's machine-readable projection
 * `test-infra/harness/tier-capabilities.generated.json`.
 *
 * Why generated, not hand-written (single-source patterns 1 + 2):
 *   tier-matrix.json is THE source of truth for the product's tier
 *   boundaries (verify-tier-parity.ts cross-references it against backend
 *   gates + frontend guards). The MicroVM test harness needs the same
 *   boundary map at runtime to assert tier-unlock / tier-refusal. Hand-
 *   maintaining a second copy in the harness would drift the instant the
 *   matrix changes. Instead the harness reads this generated projection,
 *   and `audit:harness-tier-parity` fails on any drift.
 *
 * The projection layers the enforcement axis onto the product axis:
 *   - product_tier     = the feature's `minimumTier` (4-tier marketing axis)
 *   - enforcement_tier = product_tier mapped through _enforcementMap. Solo
 *                        and Team both currently sign as the `weaver` code
 *                        tier (Decision #87/#185) until the v2.2 federation
 *                        flip. The harness asserts gates against this 3-tier
 *                        enforcement axis while tracking Solo vs Team
 *                        distinctly via product_tier.
 *
 * Output is deterministic — capability ids are sorted, no timestamps, no
 * per-run identifiers — so `audit:generated-artifact-freshness`-style diff
 * checks see real drift, not churn.
 *
 * Invocation:
 *   npx tsx scripts/gen-tier-capabilities.ts
 *   or: npm run --prefix code generate:tier-capabilities
 *
 * Exit codes:
 *   0 — projection written
 *   1 — source parse error or I/O failure
 */

import { readFileSync, writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const CODE_ROOT = resolve(__dirname, '..')
const PROJECT_ROOT = resolve(CODE_ROOT, '..')

const SOURCE = resolve(CODE_ROOT, 'tier-matrix.json')
const ARTIFACT = resolve(PROJECT_ROOT, 'test-infra', 'harness', 'tier-capabilities.generated.json')

// Product (marketing) tiers — the 4-tier axis the harness vocabulary uses.
const PRODUCT_TIERS = ['free', 'solo', 'team', 'fabrick'] as const
// Enforcement (code) tiers — what the license layer actually signs today.
const ENFORCEMENT_TIERS = ['free', 'weaver', 'fabrick'] as const
// product_tier → enforcement_tier. Solo + Team both enforce as `weaver`
// until the v2.2 federation flip (Decision #87/#185).
const ENFORCEMENT_MAP: Record<string, string> = {
  free: 'free',
  solo: 'weaver',
  team: 'weaver',
  fabrick: 'fabrick',
}

interface MatrixFeature {
  id: string
  minimumTier: string
  implemented: boolean
  scope?: string
  family?: string
}

interface Matrix {
  features: MatrixFeature[]
}

interface Capability {
  product_tier: string
  enforcement_tier: string
  implemented: boolean
  scope: string
  family: string | null
}

function main(): void {
  let matrix: Matrix
  try {
    matrix = JSON.parse(readFileSync(SOURCE, 'utf8')) as Matrix
  } catch (e) {
    console.error(`gen-tier-capabilities: failed to read/parse ${SOURCE}`)
    console.error((e as Error).message)
    process.exit(1)
  }

  if (!Array.isArray(matrix.features)) {
    console.error('gen-tier-capabilities: tier-matrix.json has no "features" array')
    process.exit(1)
  }

  // Sort by id for deterministic output.
  const sorted = [...matrix.features].sort((a, b) => a.id.localeCompare(b.id))

  const capabilities: Record<string, Capability> = {}
  for (const f of sorted) {
    const productTier = f.minimumTier
    const enforcementTier = ENFORCEMENT_MAP[productTier]
    if (!enforcementTier) {
      console.error(
        `gen-tier-capabilities: feature "${f.id}" has unknown minimumTier "${productTier}" ` +
          `(expected one of ${PRODUCT_TIERS.join(', ')})`,
      )
      process.exit(1)
    }
    capabilities[f.id] = {
      product_tier: productTier,
      enforcement_tier: enforcementTier,
      implemented: f.implemented,
      scope: f.scope ?? 'none',
      family: f.family ?? null,
    }
  }

  const output = {
    _generated:
      'GENERATED by code/scripts/gen-tier-capabilities.ts — do not edit by hand. ' +
      'Source: code/tier-matrix.json. Regenerate: npm run --prefix code generate:tier-capabilities',
    _productTiers: [...PRODUCT_TIERS],
    _enforcementTiers: [...ENFORCEMENT_TIERS],
    _enforcementMap: ENFORCEMENT_MAP,
    capabilities,
  }

  // Trailing newline for POSIX-friendly diffs.
  writeFileSync(ARTIFACT, JSON.stringify(output, null, 2) + '\n', 'utf8')

  console.log(
    `gen-tier-capabilities: wrote ${Object.keys(capabilities).length} capabilities → ` +
      `test-infra/harness/tier-capabilities.generated.json`,
  )
}

main()
