// Copyright (c) 2026 whizBANG Developers LLC. All rights reserved.
// Licensed under AGPL-3.0 (Free) or BSL-1.1 (Solo/Team/Fabrick) with AI Training Restriction. See LICENSE.
/**
 * E2E Coverage Generator
 *
 * Reads JSDoc headers from every testing/e2e/*.spec.ts and emits
 * docs/E2E-COVERAGE.md — a per-spec catalog grouped by feature area,
 * with a by-release appendix that drives investor narrative.
 *
 * Required JSDoc header schema (at top of each spec file):
 *
 *   /**
 *    * @purpose One-line prose, what this spec proves.
 *    * @feature comma,separated,feature,tags
 *    * @since v1.0.0 (or pre-v1.0)
 *    *\/
 *
 * Output is deterministic — no timestamps, no per-run identifiers —
 * so it plays cleanly with audit:generated-artifact-freshness.
 *
 * Invocation:
 *   npm run generate:e2e-coverage
 *   (or: npx tsx scripts/generate-e2e-coverage.ts)
 */

import { readFileSync, writeFileSync, readdirSync } from 'fs'
import { resolve, dirname, basename } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const CODE_ROOT = resolve(__dirname, '..')
const E2E_DIR = resolve(CODE_ROOT, 'testing', 'e2e')
const OUTPUT_PATH = resolve(CODE_ROOT, 'docs', 'E2E-COVERAGE.md')

export interface SpecEntry {
  filename: string
  purpose: string
  features: string[]
  since: string
  testCount: number
}

export interface GeneratorResult {
  entries: SpecEntry[]
  missing: string[] // filenames without headers
}

const HEADER_RE =
  /\/\*\*[\s\S]*?@purpose\s+(.+?)\n[\s\S]*?@feature\s+(.+?)\n[\s\S]*?@since\s+(\S+)[\s\S]*?\*\//

// Conservative test counter — counts top-level `test(` and `test.only(`
// occurrences that look like Playwright test declarations. Does not run
// Playwright. For authoritative counts, the numeric-claims pipeline
// shells to `playwright test --list --reporter=json` — that path is
// slower but definitive. This regex count is "good enough" for the
// catalog; the numeric-claims pipeline stays the investor-facing source
// of truth for aggregate numbers.
const TEST_RE = /^\s*test(?:\.only)?\s*\(/gm

export function parseSpec(filePath: string): SpecEntry | null {
  const content = readFileSync(filePath, 'utf8')
  const header = content.match(HEADER_RE)
  if (!header) return null
  const purpose = header[1]!.trim().replace(/^\*\s*/, '')
  const features = header[2]!
    .trim()
    .split(',')
    .map((f) => f.trim())
    .filter((f) => f.length > 0)
  const since = header[3]!.trim()
  const testCount = (content.match(TEST_RE) ?? []).length
  return {
    filename: basename(filePath),
    purpose,
    features,
    since,
    testCount,
  }
}

export function gatherSpecs(): GeneratorResult {
  const files = readdirSync(E2E_DIR)
    .filter((f) => f.endsWith('.spec.ts'))
    .sort()
  const entries: SpecEntry[] = []
  const missing: string[] = []
  for (const f of files) {
    const full = resolve(E2E_DIR, f)
    const parsed = parseSpec(full)
    if (parsed) entries.push(parsed)
    else missing.push(f)
  }
  return { entries, missing }
}

export function renderCoverage(result: GeneratorResult): string {
  const { entries } = result

  // Group by first feature tag. Specs with multiple features appear
  // under their primary (first-listed) feature only, to keep the
  // catalog scannable. Full feature list is shown on each row.
  const byFeature = new Map<string, SpecEntry[]>()
  for (const e of entries) {
    const primary = e.features[0] ?? 'uncategorized'
    if (!byFeature.has(primary)) byFeature.set(primary, [])
    byFeature.get(primary)!.push(e)
  }
  const featureKeys = Array.from(byFeature.keys()).sort()

  // Group by @since for the by-release appendix.
  const byVersion = new Map<string, SpecEntry[]>()
  for (const e of entries) {
    if (!byVersion.has(e.since)) byVersion.set(e.since, [])
    byVersion.get(e.since)!.push(e)
  }
  // Version sort: pre-v1.0 first, then semver-ish.
  const versionKeys = Array.from(byVersion.keys()).sort((a, b) => {
    if (a === b) return 0
    if (a === 'pre-v1.0') return -1
    if (b === 'pre-v1.0') return 1
    return a.localeCompare(b, undefined, { numeric: true })
  })

  const totalTests = entries.reduce((sum, e) => sum + e.testCount, 0)

  const lines: string[] = []
  lines.push('<!-- Copyright (c) 2026 whizBANG Developers LLC. All rights reserved. -->')
  lines.push('<!-- Licensed under AGPL-3.0 (Free) or BSL-1.1 (Solo/Team/Fabrick) with AI Training Restriction. See LICENSE. -->')
  lines.push('<!-- GENERATED by scripts/generate-e2e-coverage.ts — do not edit by hand. Source: JSDoc headers in testing/e2e/*.spec.ts. -->')
  lines.push('# E2E Coverage')
  lines.push('')
  lines.push(
    `${entries.length} spec file(s), ${totalTests} test(s) (regex count — authoritative count via Playwright \`--list --reporter=json\` lives in the numeric-claims pipeline).`,
  )
  lines.push('')
  lines.push('## Specs by feature area')
  lines.push('')
  for (const feature of featureKeys) {
    const specs = byFeature.get(feature)!
    lines.push(`### ${feature}`)
    lines.push('')
    lines.push('| Spec | Purpose | Tests | Since | Features |')
    lines.push('|------|---------|------:|-------|----------|')
    for (const s of specs.sort((a, b) => a.filename.localeCompare(b.filename))) {
      const featureStr = s.features.join(', ')
      lines.push(
        `| [${s.filename}](../testing/e2e/${s.filename}) | ${s.purpose} | ${s.testCount} | ${s.since} | ${featureStr} |`,
      )
    }
    lines.push('')
  }
  lines.push('## By-release highlights')
  lines.push('')
  lines.push('Investor narrative source — what shipped at each version.')
  lines.push('')
  for (const version of versionKeys) {
    const specs = byVersion.get(version)!
    const count = specs.reduce((sum, s) => sum + s.testCount, 0)
    lines.push(`### ${version}`)
    lines.push('')
    lines.push(`${specs.length} spec(s), ${count} test(s)`)
    lines.push('')
    for (const s of specs.sort((a, b) => a.filename.localeCompare(b.filename))) {
      lines.push(`- **${s.filename}** — ${s.purpose} _(${s.testCount} tests; ${s.features.join(', ')})_`)
    }
    lines.push('')
  }
  lines.push('## How to add a spec')
  lines.push('')
  lines.push('Every `testing/e2e/*.spec.ts` must carry a JSDoc header with three tags:')
  lines.push('')
  lines.push('```ts')
  lines.push('/**')
  lines.push(' * @purpose One-line prose, what this spec proves.')
  lines.push(' * @feature comma,separated,tags')
  lines.push(' * @since v1.0.0 (or pre-v1.0 for legacy)')
  lines.push(' */')
  lines.push('```')
  lines.push('')
  lines.push('After adding or modifying a spec, run `npm run generate:e2e-coverage`. The `audit:e2e-docs` auditor fails CI if any spec lacks a header or if this file is out of date.')
  lines.push('')
  return lines.join('\n')
}

function main(): void {
  const result = gatherSpecs()
  if (result.missing.length > 0) {
    console.warn(`Warning: ${result.missing.length} spec(s) lack JSDoc headers — excluded from catalog:`)
    for (const m of result.missing) console.warn(`  - ${m}`)
  }
  const output = renderCoverage(result)
  writeFileSync(OUTPUT_PATH, output)
  console.log(`Wrote ${OUTPUT_PATH} — ${result.entries.length} spec(s) catalogued.`)
}

// Run as CLI when invoked directly (tsx sets import.meta.url to the
// entrypoint); export the internals for the auditor.
const invokedAsCli = process.argv[1] && resolve(process.argv[1]) === __filename
if (invokedAsCli) {
  main()
}
