// Copyright (c) 2026 whizBANG Developers LLC. All rights reserved.
// Licensed under AGPL-3.0 (Free) or BSL-1.1 (Solo/Team/Fabrick) with AI Training Restriction. See LICENSE.

/**
 * Generate `backend/src/generated/license-authority.ts` from `backend/src/license-authority.json`.
 *
 * Uses the **vendored** `resolveChannel`, not a checkout of `wbd-entitlement`. That is not a
 * stylistic choice: `backend/src/` and `scripts/` both ship to Weaver-Free, and a public clone has
 * no access to the private repo. A generator that shelled out to one would make the Free repo
 * unbuildable by anyone outside WBD — which for an AGPL work is a licence problem, not an
 * inconvenience.
 *
 * ## Why the artifact is committed
 *
 * `wbd-entitlement` gitignores its equivalent because it is channel-dependent. Here the channel
 * that matters is `release`, it is deterministic from the manifest, and a public clone must be
 * able to typecheck without running a generator first — so this follows Weaver's own pattern 1
 * (full artifact from source, generator, freshness auditor, pre-commit hook) instead.
 *
 * A dev build that needs to trust a test authority regenerates with `--channel dev`, which shows
 * up as a dirty tree. That is honest rather than annoying: a build trusting a non-production key
 * should be visible.
 *
 * Run:   npx tsx scripts/generate-license-authority.ts [--channel release] [--allow-empty]
 * Check: npm run audit:generated-artifact-freshness   (this generator is registered there)
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname } from 'node:path'
import { parseArgs } from 'node:util'
import {
  parseManifest,
  resolveChannel,
  RELEASE_CHANNELS,
} from '../backend/src/entitlement/format/authority.js'

export const MANIFEST = new URL('../backend/src/license-authority.json', import.meta.url).pathname
export const OUT = new URL('../backend/src/generated/license-authority.ts', import.meta.url).pathname

/** Build the module text. Exported so the freshness auditor compares against the same function. */
export function renderAuthority(channel: string, keys: readonly string[]): string {
  return `// Copyright (c) 2026 whizBANG Developers LLC. All rights reserved.
// Licensed under AGPL-3.0 (Free) or BSL-1.1 (Solo/Team/Fabrick) with AI Training Restriction. See LICENSE.
//
// GENERATED by scripts/generate-license-authority.ts — do not edit by hand.
// Source: backend/src/license-authority.json (channel: ${channel})
//
// This file is the ONLY legitimate origin of verification material in a Weaver build. Nothing here
// may read process.env, a config file, or any other runtime input: the party a licence restricts is
// the operator, so verification material an operator supplies is not verification. Enforced by
// audit:authority-binding, not merely asserted by this comment.

/** The channel this artifact was built for. */
export const CHANNEL = ${JSON.stringify(channel)} as const

/** Whether this artifact is customer-facing. Release builds never trust a test authority. */
export const IS_RELEASE = ${RELEASE_CHANNELS.includes(channel)}

/**
 * Public keys this build accepts, base64url raw Ed25519, **newest first**.
 *
 * Empty means every licence fails to verify and the host resolves to Free — the fail-closed
 * direction, and the correct state until the production keypair ceremony has run. Do not
 * "temporarily" add a key to get past it.
 */
export const ACCEPTED_PUBLIC_KEYS: readonly string[] = ${JSON.stringify(keys, null, 2)}
`
}

/**
 * Resolve a channel, tolerating the deliberate pre-ceremony empty state — and ONLY that.
 *
 * `unknown channel` used to be swallowed alongside `resolves to no keys`, which conflates two
 * opposite conditions. An empty channel is a state someone chose and declared; an unknown one is
 * a TYPO, and swallowing it writes a module stamped with the misspelling, trusting nothing, at
 * exit 0. Every licence then resolves to Free and the artifact looks deliberate.
 *
 * It is live today rather than hypothetical: `allowEmpty` is switched on automatically while the
 * manifest holds no keys, so `--channel realese` is currently a silent success. The window closes
 * once a key exists, which is an argument for fixing it now — after the ceremony the same typo
 * fails, so nobody would ever find this by hitting it.
 */
export function resolveOrEmpty(channel: string, allowEmpty: boolean): string[] {
  const manifest = parseManifest(JSON.parse(readFileSync(MANIFEST, 'utf-8')))
  try {
    return resolveChannel(manifest, channel)
  } catch (err) {
    // Only the declared-but-empty case is tolerable. An unknown channel is always a mistake.
    const isEmpty = err instanceof Error && /resolves to no keys/.test(err.message)
    if (allowEmpty && isEmpty) return []
    throw err
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { values } = parseArgs({
    options: { channel: { type: 'string' }, 'allow-empty': { type: 'boolean' } },
  })
  const channel = values.channel ?? 'release'
  // Pre-ceremony the manifest legitimately has no keys, so allow-empty defaults on for `release`
  // ONLY while the manifest declares no keys at all. Once a key exists, an empty release channel
  // means someone deleted it, and that must fail.
  const manifest = parseManifest(JSON.parse(readFileSync(MANIFEST, 'utf-8')))
  const preCeremony = Object.keys(manifest.keys).length === 0
  const keys = resolveOrEmpty(channel, values['allow-empty'] || preCeremony)

  if (keys.length === 0) {
    console.error(
      `generate-license-authority: channel '${channel}' has NO keys.\n` +
        '  This build verifies nothing and every licence resolves to Free. Correct before the\n' +
        '  ceremony; a bug afterwards.',
    )
  }

  mkdirSync(dirname(OUT), { recursive: true })
  writeFileSync(OUT, renderAuthority(channel, keys))
  console.log(`generate-license-authority: ${channel} → ${keys.length} key(s)`)
}
